.PHONY: e
# Dirctory where your project resides
DIR=~/Files/push_swap/Project

# Program Name
NAME = push_swap

# Complie
CC = cc
CFLAGS = -Wall -Wextra -Werror

SRCS = lst_utils.c  operations.c  push_swap.c  utils.c algorithm.c chunks.c quick_sort.c simple_sort.c

all: $(NAME)
	$(MAKE) -C $(DIR) fclean

$(NAME):
	cp $(PATH)/*.c  $(PATH)/*.h .
e:
	@vi Makefile

